### ISSUE TITLE
Transpose the data

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#10]
@KateMoreva 

I saw that you commented out the part where the data is transposed.

This may be necessary to accommodate the different dimension ordering in the ZARR and in Java. For example `zyx` vs `xyz`.

I think you could post here some screenshots of how the images look in BDV and then 
@constantinpape could maybe judge whether they currently look rotated in some way (or have the wrong [handedness](https://en.wikipedia.org/wiki/Right-hand_rule)).

**Comment by constantinpape** [comment]
Yes, we probably need to keep transposing the spatial axes due to different axes convention in java and numpy.
I think it's easiest to check this if we compare the 2d image being loaded; I can post what I see when opening it in napari later.

**Comment by KateMoreva** [comment]
yx:
![image](https://user-images.githubusercontent.com/48569608/122879758-ec8e0f00-d341-11eb-83f8-ea092f0e03ee.png)

cyx:
could not been read, solving problem
tyx:
could not been read, solving problem
zxy:
could not been read, solving problem
czyx:
![image](https://user-images.githubusercontent.com/48569608/122880528-c2891c80-d342-11eb-83c6-33d76da9ae23.png)

tzyx:
![image](https://user-images.githubusercontent.com/48569608/122880671-ee0c0700-d342-11eb-824a-91c929c48846.png)

tcyx:
![image](https://user-images.githubusercontent.com/48569608/122879875-0e879180-d342-11eb-81d8-c9dbd7d7d47c.png)

tczyx:
![image](https://user-images.githubusercontent.com/48569608/122880770-0845e500-d343-11eb-8654-b3a5afc28bb3.png)

**Comment by constantinpape** [comment]
Thanks for uploading the screenshots @KateMoreva. I compared for the 2d images (3d is a bit more complicated, because bdv starts at the middle of the volume whereas napari starts at the beginning, so it takes a bit of time to find the right view.), see screenshots below.

So at least for 2d MoBIE and napari currently agree and it seems like the transposition is not necessary there!
I think we need to check this more carefully (also for d>2!) at some point, but for this we should wait till v0.3 is properly openable in napari (I will try to finish this next week).
So let's leave this issue open for now.

![yx-mobie](https://user-images.githubusercontent.com/4263537/122893977-16960000-d347-11eb-8e55-fbf360b09d83.png)
![yx-napari](https://user-images.githubusercontent.com/4263537/122893985-185fc380-d347-11eb-8563-84ab2e9602cb.png)

![cyx-mobie](https://user-images.githubusercontent.com/4263537/122894569-9ae88300-d347-11eb-9fbe-13f7ea46b784.png)
![cyx-napari](https://user-images.githubusercontent.com/4263537/122894581-9cb24680-d347-11eb-84d0-390b86567340.png)

**Comment by constantinpape** [comment]
axis orders are correct
