### ISSUE TITLE
deployment to maven failed

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#132]
@imagejan @ctrueden 
do you understand what the issue here is?
https://github.com/mobie/mobie-io/actions/runs/3967527353/jobs/6799593543#step:5:395

**Comment by ctrueden** [comment]
@tischi The problem is:
> Could not transfer artifact org.apache.maven:maven-archiver:pom:3.5.0 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/3.5.0/maven-archiver-3.5.0.pom: Connection timed out

Which suggests Maven Central might have been temporarily overloaded or down, or perhaps blocking the CI's IP address due to anti-abuse automation.

Does it work now if you rerun the build? Not much we can do about Maven Central behavior on our side. If you still have problems, you could avoid the issue by using maven.scijava.org as sole mirror to download all artifacts, and avoid talking directly to Central.

**Comment by tischi** [comment]
thanks @ctrueden I will keep trying  then (re-ran once and same error).

**Comment by ctrueden** [comment]
If the problem doesn't clear up, and you want to try the maven.scijava.org mirror route, the way it works is to make a file `~/.m2/settings.xml` on the CI side with contents:
```
<?xml version="1.0"?>
<settings>
	<mirrors>
		<mirror>
			<id>scijava-mirror</id>
			<name>SciJava mirror</name>
			<url>https://maven.scijava.org/content/groups/public</url>
			<mirrorOf>*</mirrorOf>
		</mirror>
	</mirrors>
</settings>
```
And then the Maven build will only ask maven.scijava.org for all artifacts.

If you commit such a file to `/.ci/settings.xml` in your GitHub repository, the `ci-build.sh` script will automatically copy it to the right place for you upon each build, rather than generating one from scratch. But you would also need to add [all this junk](https://github.com/scijava/scijava-scripts/blob/a2c8fae403556b12996f2dc92b327b2e47170cc0/ci-build.sh#L87-L119) to the file as well in order for deploys to maven.scijava.org to continue working.

**Comment by tischi** [comment]
Now it did build: https://github.com/mobie/mobie-io/actions/runs/3967527353
Seems to have been something temporary...
Thanks @ctrueden for the suggestions!
